// Read/write the singleton project_context row. The reply route reads
// these fields into the LLM prompt so drafted replies stay grounded in
// the user's actual project (not generic "great question!" fluff).
//
// Shape: a structured ProjectDocumentation block the agent generated by
// reading the repo, plus a typed Questions/Answers exchange so the user
// fills in ambiguity points the code can't reveal (target audience, tone,
// things to never claim, etc).

import { getDb } from "../db.js";

export type ProjectDocumentation = {
  // One-paragraph synthesis of what the project does. Written from the
  // agent's voice, not marketing copy.
  summary: string;
  // 3-5 short bullets the agent identified as the headline features.
  key_features: string[];
  // 3-8 strings: languages, frameworks, infra. Pulled from package.json /
  // imports / file extensions.
  tech_stack: string[];
  // One sentence: who the project is for.
  target_audience: string;
  // One sentence: how the assistant should sound when replying on behalf
  // of this project. Inferred from README tone.
  voice_guidance: string;
  // 1-3 strings: claims / framings the assistant should NOT make. Often
  // populated by the user's answers to clarifying questions.
  things_to_avoid: string[];
};

// One option in a single-choice question. `description` is optional inline
// help, mirroring Claude Code's AskUserQuestion shape.
export type ProjectQuestionOption = {
  label: string;
  description?: string;
};

// Two question types are supported today. `mcq` is single-choice with
// labeled options; `text` is free-form.
export type ProjectQuestion =
  | {
      id: string;
      type: "mcq";
      text: string;
      options: ProjectQuestionOption[];
    }
  | { id: string; type: "text"; text: string };

export type ProjectAnswer = { id: string; answer: string };

export type ProjectContext = {
  repo_url: string | null;
  documentation: ProjectDocumentation | null;
  questions: ProjectQuestion[];
  answers: ProjectAnswer[];
  updated_at: number | null;
};

type Row = {
  repo_url: string | null;
  documentation_json: string | null;
  questions_json: string | null;
  answers_json: string | null;
  updated_at: number;
};

function safeJsonParse<T>(s: string | null, validate: (v: unknown) => v is T): T | null {
  if (!s) return null;
  try {
    const parsed = JSON.parse(s);
    return validate(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function isDoc(v: unknown): v is ProjectDocumentation {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o.summary === "string" &&
    Array.isArray(o.key_features) &&
    Array.isArray(o.tech_stack) &&
    typeof o.target_audience === "string" &&
    typeof o.voice_guidance === "string" &&
    Array.isArray(o.things_to_avoid)
  );
}

function isQuestionArray(v: unknown): v is ProjectQuestion[] {
  if (!Array.isArray(v)) return false;
  return v.every((q) => {
    if (typeof q !== "object" || q === null) return false;
    const o = q as Record<string, unknown>;
    if (typeof o.id !== "string" || typeof o.text !== "string") return false;
    if (o.type === "mcq") return Array.isArray(o.options);
    if (o.type === "text") return true;
    return false;
  });
}

function isAnswerArray(v: unknown): v is ProjectAnswer[] {
  if (!Array.isArray(v)) return false;
  return v.every(
    (a) =>
      typeof a === "object" &&
      a !== null &&
      typeof (a as Record<string, unknown>).id === "string" &&
      typeof (a as Record<string, unknown>).answer === "string",
  );
}

export function getProjectContext(): ProjectContext {
  const db = getDb();
  const row = db
    .prepare(
      `SELECT repo_url, documentation_json, questions_json, answers_json, updated_at
         FROM project_context WHERE id = 1`,
    )
    .get() as Row | undefined;

  if (row === undefined) {
    return {
      repo_url: null,
      documentation: null,
      questions: [],
      answers: [],
      updated_at: null,
    };
  }

  return {
    repo_url: row.repo_url,
    documentation: safeJsonParse(row.documentation_json, isDoc),
    questions: safeJsonParse(row.questions_json, isQuestionArray) ?? [],
    answers: safeJsonParse(row.answers_json, isAnswerArray) ?? [],
    updated_at: row.updated_at,
  };
}

export function setProjectContext(
  patch: Partial<{
    repo_url: string;
    documentation: ProjectDocumentation;
    questions: ProjectQuestion[];
    answers: ProjectAnswer[];
  }>,
): ProjectContext {
  const db = getDb();
  const current = getProjectContext();
  const next = {
    repo_url: patch.repo_url ?? current.repo_url,
    documentation: patch.documentation ?? current.documentation,
    questions: patch.questions ?? current.questions,
    answers: patch.answers ?? current.answers,
  };
  db.prepare(
    `INSERT INTO project_context
       (id, repo_url, documentation_json, questions_json, answers_json, updated_at)
       VALUES(1, ?, ?, ?, ?, unixepoch())
     ON CONFLICT(id) DO UPDATE SET
       repo_url           = excluded.repo_url,
       documentation_json = excluded.documentation_json,
       questions_json     = excluded.questions_json,
       answers_json       = excluded.answers_json,
       updated_at         = excluded.updated_at`,
  ).run(
    next.repo_url,
    next.documentation ? JSON.stringify(next.documentation) : null,
    JSON.stringify(next.questions),
    JSON.stringify(next.answers),
  );
  return getProjectContext();
}

// Format the stored context as a single string suitable for prepending to
// an LLM prompt. Returns null if no context has been captured yet so
// callers can decide whether to skip the section entirely.
export function projectContextForPrompt(): string | null {
  const ctx = getProjectContext();
  if (!ctx.documentation && ctx.answers.length === 0) return null;
  const lines: string[] = ["--- Project context ---"];
  const d = ctx.documentation;
  if (d) {
    lines.push(`Project: ${d.summary}`);
    if (d.key_features.length > 0)
      lines.push(`Key features: ${d.key_features.join("; ")}`);
    if (d.tech_stack.length > 0)
      lines.push(`Tech: ${d.tech_stack.join(", ")}`);
    if (d.target_audience)
      lines.push(`Target audience: ${d.target_audience}`);
    if (d.voice_guidance) lines.push(`Voice: ${d.voice_guidance}`);
    if (d.things_to_avoid.length > 0)
      lines.push(`Never claim: ${d.things_to_avoid.join("; ")}`);
  }
  if (ctx.answers.length > 0 && ctx.questions.length > 0) {
    // Pair answers back to their original questions for the prompt.
    const byId = new Map(ctx.questions.map((q) => [q.id, q]));
    for (const a of ctx.answers) {
      const q = byId.get(a.id);
      if (!q || !a.answer.trim()) continue;
      lines.push(`Q (${q.text}): A: ${a.answer}`);
    }
  }
  return lines.join("\n");
}
